language: node_js
node_js:
- '8'
install:
  - npm install -g istanbul
  - npm install -g codecov
  - npm install -g mocha
script:
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
- codecov
