language: node_js
node_js:
- '8'
before_install:
- sudo apt-get update -qq
- sudo apt-get install mpv
script:
- npm run test
env:
  global:
  - secure: GL7OipQeSqJTDDqRUyIYHHpAWQWe7zx7ghR7DIUf3TqWxexUo7XMxg55ui6BoKVcFU6nZn/4u88631CK/OCLnYR1QO30Km/yKIZbG3pObTLnegtSmRyVBAH8vWoOhy5mcpvDWNHCK23NfYV1yLNgry/bAfVfV7AI2m8zKhlo0v7yLCgDbianNHyGFItaHGL0mETDr+qRDGsXzczPN46YyM4YjWnjxTEkQpqUVhH1SNZ3PxbOydDz57GpcrDPyAlIyLKF73Rqjj4TXFvxOWMLp6RSYw0N4rzL1aTA55T/I+eODGrvxT43CRzL04thNTcmScwNrNkhG9oyJW1aTzFlISC1EL/ZrF4YvgVo+ilgk/zj4GlWLOb8liwwhI7o/oDxJr9aoaz3RpgKuEWp8p0UNR5yDj/g8I7ipdhBaJLbd4mPsB8ZA7DDxgUJ9lWM4APC672uoIIct2PBGm7OXBBZSmCBJf9kdR5JdF4Gw2cQD+LUeUtOfF+tjc81OVryY+0WnbsNfk3aM3UwD40WxoDhuGnV9Hzb6YFFz+4RLeDI6ZQjgjFG2jlzabeiF7J/Zh0S8Tqmq9uMx0DQMa4qUkI8Is5yVWYpBIcUoecNUDR7q8W7JWQbqUxC2TZNSiQPW+kBu5nuYTWfDlfnmAi1WREE3JnE+BZy219tXs1Z2XM/RcI=
  - secure: giCurQsCC7jFzmUOHe/nkuC5xJ2OobpMJbVByIAiSukJvi6pQjMs4wndiyABUAnUbUr/BLg8yeTmKyf4ot3GghqOixvxsZtWRd8UsRv5aHUGOOWMX/THpvIQfiiserhVmJdWj0UNVKdkNtxf09yhpMaFrdOVxW30leGbSaSYiRVfAkRUUFPaCf5VgCY36UmFpaJqu0efuneDe1JC3POH7vCFJtHvztpxYGWPWYfi8Z4o7n/P8yJ6s05NR2Yrqq7OmsRAHyC/tSn093KDAo5HkLCXDLX+yD5ivYLhADKTEe6JmD2sTuWEB/nLI3pEyPY2oA2lsID9DTx6hgYIVg6VAAlf49ZTlajuYzAPozcLkM03EO/QSpa4xGYYizfvuokLdKV9pJdOg4M6P/73j3zAbuhtJandVz8EQJ4+VGLyRLvuAFELY5vWVN5JQF4DI3Z8FGkz+kunBt9UWTTBRrnl2a9kxYEnfwOvdG6OgVgSmkhMaRpoEYcXRLUIkeGRRXhrPK/6TYSuFe+GltwNmKevb6dT8eKtrmQsWEF1qc1pZUCM7L7rfvqMFvid0yQ8/J7bmvuYzOdTkKDpvnkWzQJm96IspPlVFzexl6bVnFZ8YW+sD9DuRQ7Mmxk24liPjliErlXiMI2iVr6DAdiLI1NY6aXN7ZQ5R6GbPgxV2ECp/oY=
